##############################################################
#                                                            #
#                  Setup PostgreSQL service                  #
#                                                            #
##############################################################

- name: Allow password authentication for local socket users
  copy:
    src: "pg_hba.conf"
    dest: "/etc/postgresql/9.3/main/pg_hba.conf"
    force: yes
  notify: Restart Postgres

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Create User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
    role_attr_flags: "SUPERUSER,CREATEDB"

- name: Provide user with DB permissions
  become: yes
  become_user: postgres
  postgresql_user:
    user: "{{ db_user }}"
    db: "{{ db_name }}"
    priv: "ALL"
