##############################################################
#                                                            #
#                  Install Upstart services                  #
#                                                            #
##############################################################

- name: Install Upstart script
  template:
    src: blog.conf.j2
    dest: /etc/init/blog.conf
  notify: Restart Ghost