##############################################################
#                                                            #
#                PostgreSQL Service handlers                 #
#                                                            #
##############################################################

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted